### ISSUE TITLE
New server API test plan endpoints

### ISSUE THREAD

**Issue by kvvad** [nassauwinter/zephyr-python-api#14]
It is necessary to modify server API test plan endpoints as per API:
[API link](https://support.smartbear.com/zephyr-scale-cloud/api-docs/#tag/Test-Plans/operation/getTestPlan)
Path - zephyr\scale\server\endpoints\paths.py
Actual:
![Screenshot_7](https://github.com/nassauwinter/zephyr-python-api/assets/66476813/759e793a-30b1-46ce-acab-03c428062fe0)

Expected:
![Screenshot_8](https://github.com/nassauwinter/zephyr-python-api/assets/66476813/a6fdbc3c-143d-43bc-a02d-19f28aa63ce3)

**Comment by nassauwinter** [comment]
Hi @kvvad 

You've provided me with the link to the Zephyr Scale **Cloud** API. And the file you specified is the Server one.

As I understand, new endpoints for Cloud API appeared and should be added to the package.
The server's test plan enpoints seem to be okay and there is no need to modify them.

Or is there anything I'm missing?

**Comment by nassauwinter** [comment]
Closing the ticket because of inactivity.
