### ISSUE TITLE
AutomationEndpoints are not implemented

### ISSUE THREAD

**Issue by ricky-bhatia** [nassauwinter/zephyr-python-api#5]
We are using Zephyr Scale for our project and I need to use the automation endpoints to send automation reports (cucumber) to zephyr scale cloud. However I see that those endpoints just raise NotImplementedError which means they are not yet implemented. Is there any plan to support these endpoints soon?

**Comment by nassauwinter** [comment]
Hi @ricky-bhatia

I can implement that in a week or two.

**Comment by ricky-bhatia** [comment]
> Hi @ricky-bhatia
> 
> I can implement that in a week or two.

Thank you so much @nassauwinter

**Comment by nassauwinter** [comment]
> > Hi @ricky-bhatia
> > 
> > I can implement that in a week or two.
> 
> Hi @nassauwinter 
> 
> any update on this?

Hi. Sorry for the delay. I've prepared a prototype of the function last week, but not committed it because of busy working.

It turned out that cucumber report .json file and python behave report .json have different JSON schemes. And Zephyr Cloud accepts the cucumber one. In case you use behave, you will have to use some additional formatter to make the output report file of cucumber format.

**Comment by ricky-bhatia** [comment]
> > > Hi @ricky-bhatia
> > > I can implement that in a week or two.
> > 
> > 
> > Hi @nassauwinter
> > any update on this?
> 
> Hi. Sorry for the delay. I've prepared a prototype of the function last week, but not committed it because of busy working.
> 
> It turned out that cucumber report .json file and python behave report .json have different JSON schemes. And Zephyr Cloud accepts the cucumber one. In case you use behave, you will have to use some additional formatter to make the output report file of cucumber format.

Hi @nassauwinter ! Yeah I have a cucumber JSON formatter which I use with behave. If you can commit the functions that would be of great help!

Thanks!

**Comment by nassauwinter** [comment]
Hi @ricky-bhatia

 I've merged the implementation of Cloud Automation endpoints.

**Comment by ricky-bhatia** [comment]
> Hi @ricky-bhatia
> 
> I've merged the implementation of Cloud Automation endpoints.

Thank you so much @nassauwinter !
