### ISSUE TITLE
I had to modify test_case.py -testcases +testcase

### ISSUE THREAD

**Issue by Geordie-Jon** [nassauwinter/zephyr-python-api#8]
Using the examples provided - 

# Now we can start playing with the Zephyr API!
test_cases = zscale.api.test_cases

case_data = test_cases.get_test_case(<testcase_name>)
I kept getting error 
HTTPError: Error 404. Response: b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: **/rest/atm/1.0/testcases/<testcase_name>
referencing - https://support.smartbear.com/zephyr-scale-server/api-docs/v1/
I think this should be testcase and after updating the file all seems better.

**Comment by nassauwinter** [comment]
Hi @Geordie-Jon!

Please, specify the product type you use (Server or Cloud).

What is the test name you use to retrieve the case? I mean is it a full case name or test case key, like JQA-T123?

**Comment by Geordie-Jon** [comment]
@nassauwinter 
Hi and err, yeah - bug may have been in the usage.
I only figured out the cloud stuff was running when I had no methods I was expecting from server api.
After assigning 'V1' to my ZephyrSession I found that I had ventured down the wrong path. 
Closing this issue as raised in error? :)

**Comment by nassauwinter** [comment]
You can also use class method mentioned in README.md to create a Zephyr Scale Server instance without providing the exact API version.

Enjoy! 👍
