### ISSUE TITLE
Automate Reports of zephyr scale test execution

### ISSUE THREAD

**Issue by smart-coderr** [nassauwinter/zephyr-python-api#9]
Thank you for your strong supports.

We like to automate the reporting taking activity from Zephyr scale.

Now we are manually doing following steps:
Zephyr scale App in JIRA > Reports >  Test execution results (list) > filter with 'Test Plan' > Generate > Export Excel.

We need to export this excel everyday at a particular time. Could you please share API or method to do it automatically.

**Comment by nassauwinter** [comment]
Hello @smart-coderr!

I have checked both Zephyr Scale Server and Cloud APIs. Unfortunately, there is no same official way to download reports using the APIs :(

Though, you can build this report data from available API methods. Here in the report you have a project, tests plan, end date and last test execution fields. This is an input data to build the report.

To start,  you can retrieve a test plan you need with zscale.api.test_plans.get_test_plan(...)
There you will find test runs from the received test plan data. Then you can fetch test run data: zscale.api.test_runs.get_test_results or.get_test_run. Depending on the data you need you can customize getting test executions related to the test runs.

Hope that will help you!
